version: '3.8'

services:
  db-service:
    image: postgres:latest
    environment:
      POSTGRES_DB: zicare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - default

  clinic-service:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db-service
    networks:
      - default